services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: chernet1/todo-app:latest
    command: /wait-for-it.sh db:5432 -- gunicorn --bind 0.0.0.0:8000 todo_project.wsgi:application
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "5000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8400:80"
    depends_on:
      - web
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
