version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: .
    command: /wait-for-it.sh db:5432 -- gunicorn --bind 0.0.0.0:8000 todo_project.wsgi:application
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://che:Che123@db:5432/todo_db
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
