services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-todo_db}
      POSTGRES_USER: ${DB_USER:-che}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Che123}
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DB_USER:-che} -d ${DB_NAME:-todo_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  web:
    image: chernet1/todo-app:latest
    command: >
      sh -c "
      /wait-for-it.sh db:5432 --timeout=60 --strict -- 
      python manage.py migrate --noinput &&
      python manage.py createsuperuser --noinput || true &&
      gunicorn todo_project.wsgi:application --bind 0.0.0.0:8000 
      --timeout 600
      --workers 3
      --threads 2"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER:-che}:${DB_PASSWORD:-Che123}@db:5432/${DB_NAME:-todo_db}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@gmail.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    ports:
      - "${APP_PORT:-5000}:${CONTAINER_PORT:-8000}"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_PORT:-8400}:${NGINX_CONTAINER_PORT:-80}"
    depends_on:
      - web
    networks:
      - app_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
