# install_dependencies.yml
---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
