---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install required dependencies only if they are not present
  apt:
    name:
      - docker.io
      - docker-compose
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: yes

- name: Add the user to the Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
