---
# First play to install dependencies
- name: Install dependencies for Docker deployment
  hosts: webserver
  become: yes
  tasks:
    - import_tasks: install_dependencies.yml # Use import_tasks here

# Second play to deploy the Dockerized application
- name: Deploy Dockerized application
  hosts: webserver
  become: yes

  vars:
    docker_compose_path: "/path/to/docker-compose-directory" # Update with the actual path

  tasks:
    - name: Pull the latest Docker images
      command: docker-compose pull
      args:
        chdir: "{{ docker_compose_path }}"

    - name: Start the application with Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ docker_compose_path }}"
